"use client";

import { format } from "date-fns";
import { Star } from "lucide-react";

import { cn } from "@/lib/utils";
import { OTAWordmark } from "@/components/ota-wordmark";
import {
  reviewPlatformLogo,
  reviewPlatformName,
} from "@/lib/reviews/platform-stats";
import type { Review } from "@/lib/reviews/types";

// These functions generate a consistent color for the avatar background based
// on the author's name. The color is generated by hashing the name and using
// that hash to create an HSL color. This ensures that the same author will
// always have the same color, while different authors will have different
// colors. Shared by the ReviewCard and the ReviewInspector so both stay in
// sync.
function hashString(str: string): number {
  let hash = 0;

  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) - hash + str.charCodeAt(i);
    hash |= 0;
  }

  return Math.abs(hash);
}

function seededColor(name: string) {
  const hash = hashString(name);

  // Hue gets the full color wheel.
  const hue = hash % 360;

  // Keep saturation moderate so colors don't become neon.
  const saturation = 55 + ((hash >> 8) % 16); // 55–70%

  // High lightness = consistently soft/light background.
  const lightness = 88 + ((hash >> 16) % 7); // 88–94%

  return {
    background: `hsl(${hue} ${saturation}% ${lightness}%)`,
    foreground: `hsl(${hue} ${saturation}% 25%)`,
  };
}

type ReviewAuthorHeaderProps = {
  review: Review;
  /** Size classes for the avatar circle (both `img` and initial `span`). */
  avatarClassName?: string;
  /** Name + truncation classes. Defaults to the compact card styling. */
  nameClassName?: string;
  /** Date line classes. Defaults to the compact card styling. */
  dateClassName?: string;
  /**
   * Whether to render the "from <platform>" badge on the right. The
   * ReviewInspector hides it (the source is shown in the footer) to keep the
   * top-right corner clear of the dialog's close button.
   */
  showPlatform?: boolean;
};

/**
 * Reviewer identity block: avatar (photo or seeded initial), author name,
 * formatted date, and the "from <platform>" badge. Shared by the ReviewCard
 * (compact, truncated) and the ReviewInspector (enlarged, full-width) so the
 * two never drift apart visually.
 */
export function ReviewAuthorHeader({
  review,
  avatarClassName = "size-10",
  nameClassName = "truncate text-sm font-semibold text-foreground max-w-32",
  dateClassName = "text-xs text-muted-foreground",
  showPlatform = true,
}: ReviewAuthorHeaderProps) {
  const platform = reviewPlatformName(review.source, review.platformLabel);
  const platformLogo = reviewPlatformLogo(review.source, review.platformLabel);
  const initial = review.authorName.trim().charAt(0).toUpperCase() || "?";
  const color = seededColor(review.authorName);

  return (
    <div className="flex items-start justify-between gap-3">
      <div className="flex min-w-0 items-center gap-3">
        {review.authorPhotoUrl ? (
          // Google avatar URLs need `referrerPolicy="no-referrer"`, which
          // next/image can't set — a plain <img> is intentional here.
          <img
            src={review.authorPhotoUrl}
            alt=""
            referrerPolicy="no-referrer"
            loading="lazy"
            className={cn(
              "shrink-0 rounded-full object-cover",
              avatarClassName,
            )}
          />
        ) : (
          <span
            className={cn(
              "flex shrink-0 items-center justify-center rounded-full font-semibold",
              avatarClassName,
            )}
            style={{
              backgroundColor: color.background,
              color: color.foreground,
            }}
          >
            {initial}
          </span>
        )}
        <div className="min-w-0">
          <p className={nameClassName}>{review.authorName}</p>
          <p className={dateClassName}>
            {format(new Date(review.date), "MMM d, yyyy")}
          </p>
        </div>
      </div>
      {showPlatform && (
        <span
          className="inline-flex items-center gap-1 pt-1 text-[10px] text-muted-foreground"
          aria-label={platformLogo ? `from ${platform}` : undefined}
        >
          from
          {platformLogo ? (
            <OTAWordmark ota={platformLogo} height={16} />
          ) : (
            <span>{platform}</span>
          )}
        </span>
      )}
    </div>
  );
}

type ReviewRatingProps = {
  rating: number;
  /** Size classes for each star. Defaults to the compact card styling. */
  starClassName?: string;
};

/**
 * The five-star rating row. Shared by the ReviewCard and the ReviewInspector so
 * both render the same filled/outline treatment.
 */
export function ReviewRating({
  rating,
  starClassName = "size-4",
}: ReviewRatingProps) {
  return (
    <div className="flex items-center gap-0.5">
      {[1, 2, 3, 4, 5].map((star) => (
        <Star
          key={star}
          aria-hidden="true"
          className={cn(
            starClassName,
            star <= Math.round(rating)
              ? "fill-amber-400 text-amber-400"
              : "text-border",
          )}
        />
      ))}
    </div>
  );
}
