"use client";

import { useState } from "react";
import { format } from "date-fns";
import { Star } from "lucide-react";

import { cn } from "@/lib/utils";
import { OTAWordmark } from "@/components/ota-wordmark";
import {
  reviewPlatformLogo,
  reviewPlatformName,
} from "@/lib/reviews/platform-stats";
import type { Review } from "@/lib/reviews/types";

// These functions are used in the `ReviewCard` to generate a consistent color for the avatar background based on the author's name. The color is generated by hashing the name and using that hash to create an HSL color. This ensures that the same author will always have the same color, while different authors will have different colors.
function hashString(str: string): number {
  let hash = 0;

  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) - hash + str.charCodeAt(i);
    hash |= 0;
  }

  return Math.abs(hash);
}

function seededColor(name: string) {
  const hash = hashString(name);

  // Hue gets the full color wheel.
  const hue = hash % 360;

  // Keep saturation moderate so colors don't become neon.
  const saturation = 55 + ((hash >> 8) % 16); // 55–70%

  // High lightness = consistently soft/light background.
  const lightness = 88 + ((hash >> 16) % 7); // 88–94%

  return {
    background: `hsl(${hue} ${saturation}% ${lightness}%)`,
    foreground: `hsl(${hue} ${saturation}% 25%)`,
  };
}

/** Texts longer than this (roughly 2–3 lines) get a "Read more" toggle. */
const READ_MORE_THRESHOLD = 160;

export function ReviewCard({ review }: { review: Review }) {
  const [expanded, setExpanded] = useState(false);

  const platform = reviewPlatformName(review.source, review.platformLabel);
  const platformLogo = reviewPlatformLogo(review.source, review.platformLabel);
  const initial = review.authorName.trim().charAt(0).toUpperCase() || "?";
  const hasText = review.text.trim().length > 0;
  const isLong = review.text.length > READ_MORE_THRESHOLD;
  const color = seededColor(review.authorName);

  return (
    <article className="flex h-full flex-col gap-3 rounded-2xl border bg-card p-5 text-left">
      {/* Author + platform */}
      <div className="flex items-start justify-between gap-3">
        <div className="flex min-w-0 items-center gap-3">
          {review.authorPhotoUrl ? (
            // Google avatar URLs need `referrerPolicy="no-referrer"`, which
            // next/image can't set — a plain <img> is intentional here.
            <img
              src={review.authorPhotoUrl}
              alt=""
              referrerPolicy="no-referrer"
              loading="lazy"
              className="size-10 shrink-0 rounded-full object-cover"
            />
          ) : (
            <span
              className="flex size-10 shrink-0 items-center justify-center rounded-full font-semibold"
              style={{
                backgroundColor: color.background,
                color: color.foreground,
              }}
            >
              {initial}
            </span>
          )}
          <div className="min-w-0">
            <p className="truncate text-sm font-semibold text-foreground max-w-32">
              {review.authorName}
            </p>
            <p className="text-xs text-muted-foreground">
              {format(new Date(review.date), "MMM d, yyyy")}
            </p>
          </div>
        </div>
        <span
          className="inline-flex items-center gap-1 pt-1 text-[10px] text-muted-foreground"
          aria-label={platformLogo ? `from ${platform}` : undefined}
        >
          from
          {platformLogo ? (
            <OTAWordmark ota={platformLogo} height={16} />
          ) : (
            <span>{platform}</span>
          )}
        </span>
      </div>

      {/* Stars */}
      <div className="flex items-center gap-0.5">
        {[1, 2, 3, 4, 5].map((star) => (
          <Star
            key={star}
            aria-hidden="true"
            className={cn(
              "size-4",
              star <= Math.round(review.rating)
                ? "fill-amber-400 text-amber-400"
                : "text-border",
            )}
          />
        ))}
      </div>

      {/* Text */}
      {hasText && (
        <p
          className={cn(
            "text-sm leading-relaxed text-foreground/80",
            expanded ? "" : "line-clamp-4",
          )}
        >
          {review.text}
        </p>
      )}

      {/* Actions */}
      {(isLong || review.sourceUrl) && (
        <div className="mt-auto flex items-center gap-4 pt-1">
          {isLong && (
            <button
              type="button"
              onClick={() => setExpanded((value) => !value)}
              aria-expanded={expanded}
              className="text-sm font-medium text-primary hover:underline"
            >
              {expanded ? "Read less" : "Read more"}
            </button>
          )}
          {review.sourceUrl && (
            <a
              href={review.sourceUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs font-medium text-muted-foreground hover:text-primary hover:underline"
            >
              Read on {platform}
            </a>
          )}
        </div>
      )}
    </article>
  );
}
